const fs = require("fs"), vm = require("vm"), assert = require("assert")
const C = {}
vm.runInNewContext(fs.readFileSync("plugin/Content.js", "utf8"), C)
const catalog = {current: {phase: "ready", sources: [{type: "empty", zone: "left"}]}}
assert.strictEqual(C.source(catalog, "1", "left", false), null)
assert.strictEqual(C.label(C.source(catalog, "1", "left", true)), "Empty")
assert.strictEqual(C.label(null), "Local windows")
assert.strictEqual(C.chip(null), "")
assert.strictEqual(C.state(null).text, "")
assert(C.detail(null).includes("fill order"))
assert.strictEqual(C.chip({ type: "empty", zone: "left" }), "Empty")
const app = { type: "local", zone: "left", app_class: "org.example.Editor", status: "needs-attention", error: "Open this app on the workspace" }
assert.strictEqual(C.label(app), "org.example.Editor")
assert.strictEqual(C.state(app).text, "Pending")
assert.strictEqual(C.detail(app), "Open this app on the workspace")
assert.strictEqual(C.detail({ type: "local", zone: "left", app_class: "x", status: "ready" }), "One matching window is pinned here")
// The scene header.
assert.strictEqual(C.sceneTitle(null), "No scene")
assert.strictEqual(C.sceneTitle({ phase: "none", document: null }), "No scene")
assert.strictEqual(C.sceneTitle({ phase: "restored", document: { name: "work" } }), "No scene")
assert.strictEqual(C.sceneTitle({ phase: "ready", document: {} }), "Unsaved scene")
assert.strictEqual(C.sceneTitle({ phase: "ready", document: { name: "work" } }), "work")
assert.strictEqual(C.sceneModified({ phase: "ready", modified: true, document: { name: "work" } }), true)
assert.strictEqual(C.sceneModified({ phase: "ready", modified: true, document: {} }), false)
assert.strictEqual(C.sceneModified({ phase: "restored", modified: true, document: { name: "work" } }), false)
assert.strictEqual(C.sceneMeta({ phase: "ready" }, "quad", "1"), "quad on workspace 1  ·  Ready")
assert.strictEqual(C.sceneMeta({ phase: "none" }, "quad", "1"), "quad on workspace 1")
assert.strictEqual(C.sceneMeta(null, "", ""), "")
catalog.current.phase = "restored"
assert.strictEqual(C.source(catalog, "1", "left", true), null)
const E = {}
vm.runInNewContext(fs.readFileSync("plugin/Editor.js", "utf8"), E)
const original = E.identify({ columns: [{ name: "a" }, { name: "b" }], fill: ["a", "b"] })
const a = E.findLeaf(original, "a").node.id
const renamed = E.renameZone(original, "a", "renamed")
assert.strictEqual(E.findLeaf(renamed, "renamed").node.id, a)
assert.strictEqual(E.findLeaf(E.setFill(original, ["b", "a"]), "a").node.id, a)
const split = E.splitZone(original, "a", "rows")
assert.strictEqual(E.findLeaf(split, "a").node.id, a)
assert.notStrictEqual(E.findLeaf(split, "a-2").node.id, a)
assert(!E.findLeaf(E.deleteZone(original, "a"), "a"))
const fresh = E.identify(original, true)
assert.notStrictEqual(fresh.layout_id, original.layout_id)
assert.notStrictEqual(E.findLeaf(fresh, "a").node.id, a)
console.log("content and scene identities: all checks passed")
assert.equal(C.label({ type: "app", desktop_id: "remote-desktops-macbook.desktop", app_name: "MacBook" }), "MacBook")
assert.equal(C.state({ type: "app", status: "moved" }).text, "Moved")
assert.match(C.detail({ type: "app", status: "moved" }), /Moved by you/)
assert.match(C.detail({ type: "app", status: "closed" }), /Closed by you/)
